### ISSUE TITLE
IOS pre work -  tip calculator

### ISSUE THREAD

**Issue by zouruoyu** [zouruoyu/ios#1] opened 2015-09-30 21:57 UTC
/cc @codepathreview

**Comment by nickai** [comment] 2015-10-03 02:12
Nice work Ruoyo! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer learn all practical iOS development and best practices as quickly as possible. We also do a code review for each submitted project. Nice job with the project, hope you found it as a helpful introduction.

We are reviewing the submissions right now and will get in touch with you via email a few days after the submission closing date, October 9th, 2015. In the mean time, feel free to continue working on any extensions to your tip calculator app and just add a comment to this issue if you decide to do so.

Can you also add an animated gif to the Readme?

**Comment by zouruoyu** [comment] 2015-10-09 22:31
@nickai , Thanks for the comments. I have updated the code to use the new tutorial and updated README to add the animated gif.

**Comment by zouruoyu** [comment] 2015-10-09 23:22
Oops. Clicked the wrong button. I intended to say that I updated the submission to include some optional features.

**Comment by nickai** [comment] 2015-10-12 08:15
Great to see you extending your app...thanks for letting me know!

**Closed** 2015-10-26 20:07 UTC
